export const products = [
  {
    id: 1,
    name: "Luxury Jacket",
    brand: "Avant-Garde",
    price: 60,
    category: "Men",
    color: "Black",
    size: ["M", "L", "XL"],
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=1936",
    description: "Premium tailored jacket for the modern gentleman."
  },
  {
    id: 2,
    name: "Streetwear Hoodie",
    brand: "UrbanFlow",
    price: 90,
    category: "Men",
    color: "Grey",
    size: ["S", "M", "L"],
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1974",
    description: "High-quality cotton hoodie with a contemporary fit."
  },
  {
    id: 3,
    name: "Denim Jacket",
    brand: "Vintage Soul",
    price: 110,
    category: "Women",
    color: "Blue",
    size: ["S", "M"],
    image: "https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?q=80&w=1973",
    description: "Classic denim with a vintage wash and modern silhouette."
  },
  {
    id: 4,
    name: "Casual T-Shirt",
    brand: "Essentials",
    price: 40,
    category: "Men",
    color: "White",
    size: ["S", "M", "L", "XL"],
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=1974",
    description: "Breathable organic cotton tee for everyday comfort."
  },
  {
    id: 5,
    name: "Urban Sneakers",
    brand: "Stride",
    price: 130,
    category: "Accessories",
    color: "White",
    size: ["40", "41", "42", "43"],
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1912",
    description: "Sleek sneakers designed for the urban landscape."
  },
  {
    id: 6,
    name: "Classic Watch",
    brand: "Timeless",
    price: 200,
    category: "Accessories",
    color: "Gold",
    size: ["Universal"],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1999",
    description: "Timeless timepiece featuring a premium leather strap."
  },
  {
    id: 7,
    name: "Leather Bag",
    brand: "LuxStyle",
    price: 180,
    category: "Accessories",
    color: "Brown",
    size: ["Large"],
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=2069",
    description: "Handcrafted Italian leather bag for professional elegance."
  },
  {
    id: 8,
    name: "Summer Sunglasses",
    brand: "Ray-Elite",
    price: 60,
    category: "Accessories",
    color: "Black",
    size: ["One Size"],
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=2080",
    description: "UV-protected polarized sunglasses with a stylish frame."
  },
  {
    id: 9,
    name: "Slim Fit Jeans",
    brand: "Denim Co.",
    price: 95,
    category: "Women",
    color: "Dark Blue",
    size: ["28", "30", "32"],
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?q=80&w=1926",
    description: "Perfectly tailored slim fit jeans in deep indigo."
  },
  {
    id: 10,
    name: "White Sneakers",
    brand: "Minimalist",
    price: 120,
    category: "Accessories",
    color: "White",
    size: ["38", "39", "40"],
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?q=80&w=1921",
    description: "Clean minimalist sneakers that go with everything."
  },
  {
    id: 11,
    name: "Winter Coat",
    brand: "Arctic",
    price: 220,
    category: "Women",
    color: "Beige",
    size: ["M", "L"],
    image: "https://images.unsplash.com/photo-1539533377285-a92cc86725bc?q=80&w=1974",
    description: "Heavy-duty insulated coat for the coldest winters."
  },
  {
    id: 12,
    name: "Streetwear Cap",
    brand: "UrbanFlow",
    price: 35,
    category: "Accessories",
    color: "Navy",
    size: ["Adjustable"],
    image: "https://images.unsplash.com/photo-1588850567047-1845a9ee02f2?q=80&w=1964",
    description: "Embroidered five-panel cap with an adjustable strap."
  },
  // Trending Dresses Added
  {
    id: 13,
    name: "Chiffon Floral Plunge Maxi Dress",
    brand: "boohoo",
    price: 33.75,
    oldPrice: 45.00,
    category: "Women",
    color: "Floral",
    size: ["S", "M", "L"],
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=1946",
    description: "Chiffon Floral Plunge Front Floor Sweeping Maxi Dress.",
    isTrending: true,
    tag: "New Arrivals"
  },
  {
    id: 14,
    name: "Scarf Detail Trapeze Maxi Dress",
    brand: "boohoo",
    price: 22.50,
    oldPrice: 30.00,
    category: "Women",
    color: "Yellow",
    size: ["XS", "S", "M"],
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=1983",
    description: "Scarf Detail Trapeze Floor Sweeping Maxi Dress.",
    isTrending: true,
    tag: "Event Dressing"
  },
  {
    id: 15,
    name: "Chiffon Pastel Floral Ruffle Dress",
    brand: "boohoo",
    price: 27.00,
    oldPrice: 36.00,
    category: "Women",
    color: "Pastel Floral",
    size: ["M", "L", "XL"],
    image: "https://plus.unsplash.com/premium_photo-1664326554553-61ce22986445?q=80&w=1974",
    description: "Chiffon Pastel Floral Ruffle Detail Maxi Dress.",
    isTrending: true,
    tag: "Trending"
  },
  {
    id: 16,
    name: "Satin Halterneck Cowl Neck Dress",
    brand: "boohoo",
    price: 22.50,
    oldPrice: 30.00,
    category: "Women",
    color: "Peach",
    size: ["S", "M"],
    image: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=1976",
    description: "Satin Halterneck Cowl Neck Maxi Dress.",
    isTrending: true,
    tag: "Trending"
  },
  {
    id: 17,
    name: "Plus Halter Neck Scarf Maxi Dress",
    brand: "boohoo",
    price: 26.25,
    oldPrice: 35.00,
    category: "Women",
    color: "Pink",
    size: ["16", "18", "20", "22"],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070",
    description: "Plus Halter Neck Scarf Detail Flared Skirt Maxi Dress.",
    isTrending: true,
    tag: "Polka Dots"
  }
];

